### ISSUE TITLE
Failed to run /Solved

### ISSUE THREAD

**Issue by azfayel** [ihebski/angryFuzzer#1]
hello,

Is there any requirement for using angryFuzzer ?
I ran this and got an error 
[!] No module named request
Traceback (most recent call last):
  File "./angryFuzzer.py", line 29, in <module>
    sys.exit(0)
NameError: name 'sys' is not defined

Which version of python to use ?

**Comment by ihebski** [comment]
Thank you for reporting that ,To solve this one you need to install the requests packages 
`sudo pip install requests`
I will add a requirment file for all the needed libs . 
Works well with python2.7 
Happy hacking ! :+1:

**Comment by Sujay45** [comment]
Same Problem..

**Comment by Sujay45** [comment]
Mine Is Aarch64 Not Rooted. Show Same error

**Comment by abdullahbinhassan** [comment]
[!] No module named requests
Traceback (most recent call last):
  File "angryFuzzer.py", line 29, in <module>
    sys.exit(0)
NameError: name 'sys' is not defined

What to do? 
I have also given the pip install requests and it was sucessful.
Now what to do?

**Comment by ihebski** [comment]
@abdullahbinhassan 
try to install the requests lib using this command 
`sudo apt-get install python-requests` 
then 
`sudo pip install requests`
for the sys should works well if the requests is installed .

**Comment by ihebski** [comment]
@Sujay45  thank you for the report ,I have not tested the tool on Aarch64 . I will try to solve it .

**Comment by umarkhan29** [comment]
Installing python-requests works.

**Comment by benkhlifafahmi** [comment]
@abdullahbinhassan  You can fix the error simply by moving the import sys from line 20 to line 15
Note this will show you another error which is a missing module 
did you execute the command :
```bash
sudo pip install -r requirements.txt
```
